#端口号
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    username: root
    password: 888888
    url: jdbc:mysql://localhost:3306/dz_miss_activity?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    dirver-class-name: com.mysql.jdbc.Driver


